//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        public int IdRegistro { get; set; }
        public string IdHuesped { get; set; }
        public Nullable<System.DateTime> FechaHoraReserva { get; set; }
        public Nullable<System.DateTime> FechaHoraIngreso { get; set; }
        public Nullable<System.DateTime> FechaHoraFinRegistro { get; set; }
        public Nullable<decimal> TotalPago { get; set; }
        public string ReservaActiva { get; set; }
        public Nullable<System.DateTime> FechaReservaInicio { get; set; }
        public Nullable<System.DateTime> FechaReservaFinal { get; set; }
    
        public virtual ASIGNACION ASIGNACION { get; set; }
        public virtual HUESPED HUESPED { get; set; }
    }
}
