//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public int IdRegistro { get; set; }
        public string IdHuesped { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
        public Nullable<int> IdTipoDoc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int IdTransaccion { get; set; }
    
        public virtual ASIGNACION ASIGNACION { get; set; }
        public virtual TRANSACCION_DETALLE TRANSACCION_DETALLE { get; set; }
    }
}
